version: '3.9'
services:
  app:
    build:
      context: ../
      dockerfile: admin-service/Dockerfile
    environment:
      SECURITY_USER: ${SECURITY_USER}
      SECURITY_PASSWORD: ${SECURITY_PASSWORD}
      DB_URL: jdbc:postgresql://postgres:5432/${DB_NAME}?currentSchema=${DB_SCHEMA}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KC_URL: http://keycloak:8081/
      SPRING_PROFILES_ACTIVE: ${PROFILE}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: keycloak_postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
