spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak.url}/realms/${keycloak.realm}/protocol/openid-connect/certs
          issuer-uri: ${keycloak.url}/realms/${keycloak.realm}
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/v1/admin/**
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employee/**
server:
  port: 80
logging:
  level:
    root: INFO

keycloak:
  url: ${KC_URL}
  realm: ${KC_REALM}
  client-id: ${KC_CLIENT_ID}
  client-secret: ${KC_CLIENT_SECRET}