apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway-service.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "gateway-service.name" . }}
spec:
  selector:
    app: {{ include "gateway-service.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
